### ISSUE TITLE
Segmentation fault with "\A…\z"

### ISSUE THREAD

**Issue by gdeest** [rblaze/haskell-re2#4]
It looks like regexes involving the `\A` and `\z` anchors make `haskell-re2` crash matching failure. Here is an example as a GHCi session (same issue in a standalone program):

```
> :set -XOverloadedStrings
> import qualified Regex.RE2 as RE2
> pat = Data.Either.fromRight undefined $ RE2.compile "\\A(a)\\z"
> RE2.find pat "a"
Just (Match [Just "a",Just "a"])
> RE2.find pat "b"
free(): invalid pointer
```

**Comment by gdeest** [comment]
Note:

- "\\A(a)" makes the program crash as well.
- "\\Aa" does _not_.
- Neither does "(a)".

So the crash seems to originate from the combined use of a start anchor and matching groups.

**Comment by rblaze** [comment]
Thank you for reporting!

Did you test if re2 itself crashes too? haskell-re2 is just a thin wrapper
around Google's C++ regex matching library.

**Comment by rblaze** [comment]
I can't repro this. Maybe an issue with re2 itself. My library version is libre2-dev 20180201+dfsg-2
